# Configurations
markdown: kramdown
# markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: 'rouge'

# Needed for backward compatibility
gems: [jekyll-paginate]

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            "James's Blog"
tagline:          
description:      "A blog for IT work at DCGS"

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/


# Author Details
author:         'James'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       
flickr:
github:         'https://github.com/jpgibb7holman'
gplus:          
instagram:
pinterest:
linkedin:       
rss:
stackoverflow:  
twitter:        

# Google Analytics
gahandler: 'UA-74506632-1'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2
