# Needed for backward compatibility
gems: [jekyll-paginate]
# Permalinks
permalink: /blog/:year/:month/:day/:title
# Setup
title: "My blog"
description: "A blog made for IT at school"
url: "jpgibb7holman.github.io"
baseurl:
# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url: /archive/
- text: Search
  url: /search/
# Author Details
author: "James Gibb"
# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: "/blog/page:num"
